const constants = {
  POST_HERE: 'POST_HERE',
  // user posts
  GETTING_USER_POSTS: 'GETTING_USER_POSTS',
  GOT_USER_POSTS: 'GOT_USER_POSTS',
  ERROR_GETTING_POSTS: 'ERROR_GETTING_POSTS',

  SAVING_NEW_POST: 'SAVING_NEW_POST',
  SAVED_NEW_POST: 'SAVED_NEW_POST',
  ERROR_SAVING_NEW_POST: 'ERROR_SAVING_NEW_POST',
  //loginStore
  STORE_LOGIN: 'STORE_LOGIN', 
  //DS post
  SET_POST: 'SET_POST'
}

export default constants